{% set version = "0.7.2" %}

package:
  name: odm2api
  version: {{ version }}

source:
  url: https://github.com/ODM2/ODM2PythonAPI/archive/v{{ version }}.tar.gz
  sha256: 8f51dd4fff84f581905fdd1745808d3483f6c888d1aca10fbbeef4babd8f8aa6

build:
  number: 0
  skip: True  # [py3k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyodbc
    - pymysql
    - sqlalchemy
    - geoalchemy-odm2
    - shapely
    - pandas
    - psycopg2
    - six

test:
  imports:
    - odm2api

about:
  home: https://github.com/ODM2/ODM2PythonAPI
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "A Python-based application programmer's interface for the Observations Data Model 2 (ODM2)."

extra:
  recipe-maintainers:
    - emiliom
    - lsetiawan
    - ocefpaf
