{% set version = "0.7.1" %}

package:
  name: odm2api
  version: {{ version }}

source:
  url: https://github.com/ODM2/ODM2PythonAPI/archive/v{{ version }}.tar.gz
  sha256: d4c02200b904fd35447561becf0fa92d24afe6507bd50a09db57662e187e450a

build:
  number: 1000
  skip: True  # [py3k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyodbc
    - pymysql
    - sqlalchemy
    - geoalchemy-odm2
    - shapely
    - pandas
    - psycopg2
    - six

test:
  imports:
    - odm2api

about:
  home: https://github.com/ODM2/ODM2PythonAPI
  license: BSD 3-Clause
  license_file: LICENSE
  summary: "A Python-based application programmer's interface for the Observations Data Model 2 (ODM2)."

extra:
  recipe-maintainers:
    - emiliom
    - lsetiawan
    - ocefpaf
