travis:
  secure:
    BINSTAR_TOKEN: vOzr8yR+CHyxPImLITe08ifA5gptz/+Ziar62la4vjCDW4O/7vKqWwyemiZ/PdGo2tT/ILzNiV2VGz5deR+XMUV8sqS+SWEVGz2/u+6h0YD7qk6sO5tnOE5Oq4/Fh2+fqKPYCx2utBJBPGHJwawBCLjCHUmDgaGoivZL2/H0eMv00sj97oYlN5AcbV8ThHYHvEuIB8UcPJfBMwRi/5RT19Sy0MQb9V8fotav8oNTfy7utqaaFZMn5dPHkG7FO7Z0FuJ0vhGS+9C83L/iqlw/kOJW0+2jGi7nSB3R65g+uhyjNnZLvS8gO+5hziwWlBPuElTAd5gBmU9deui96jiAI18XD7XdYuXV3blxhbIiyypVULyyyyRMTIuAQH1Ms4nnpRJlXFRdy/mKT/RtFeX+omoThW6DQDYTFLkGmsj1QkYHH0znsNIsE3VHy6oOXJNLf/irmEd/PCEP6CUssrPA6e6aXUfwyz7jE0utprNJIHhIscWPE4KjvOkCxJXU6ocq7ua6WNMOySHSR8wng4CpOzjgWM8HNlqMNcuQKciTzJVXZ1ZU+wjNnB/LFoWR0VLXVnAK1SE+Aj0XEvYrD/tlhpxvVRXlSeeE/J9bQGd0ePyuFYVrMxHxgwin4aiNAHj/NhYbcGMPO7OF5ZYP96ZBupL9iJY5pv1qilEBkv50yoM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
